service: slack-dictionary-app

# 環境変数をenvで読み込ませる場合に必要
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

functions:
  app:
    handler: src/handler.app
    events:
      - http:
          method: POST
          path: /slack/events

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node14'
    define: { 'require.resolve': undefined }
    platform: node
    concurrency: 10
  serverless-offline:
    httpPort: 9000
    host: 0.0.0.0
